[package]
name = "property_tracking_"
version = "0.1.0"
authors = ["adam <adam.r.knoxg@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.2"